blank_issues_enabled: false
contact_links:
  - name: farm-ng Community Support
    url: https://discourse.farm-ng.com/
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://amiga.farm-ng.com
    about: Looking for our documentation? Find it here!
  - name: Documentation Requests / Issues
    url: https://github.com/farm-ng/amiga-dev-kit/issues/new/choose
    about: Please report your documentation requests or issues here.
